---
title: "Análise 2000: usando dados de lfp + tfr de 1980 (em linha com o paper aer ff2009)"
author: "Thais Takeuchi"
date: "2024-09-17"
output: html_document
---
## Load packages
```{r load, include = FALSE, message = FALSE, warning=FALSE}
#######################
# PREPARE ENVIRONMENT
#######################

rm(list = ls())

load.lib <- c("data.table","foreign","stargazer","devtools","stringi", "srvyr", "survey","tidyverse","gtools", "remote","installr","microdadosBrasil","ggplot2","viridis","hrbrthemes","WDI","dplyr", "arrow", "readxl","rio","writexl","dineq", "basedosdados", "httr", "haven", "openxlsx", "fixest", "readxl")

install.lib <- load.lib[!load.lib %in% installed.packages()]
for(lib in install.lib) install.packages(lib,dependencies=TRUE)
sapply(load.lib, require, character=TRUE)
```

## CENSUS
```{r census}
# dados oficiais da pea 1980 censo: 
data_1980 <- read_parquet("C:/Users/thtak/OneDrive - Fundacao Getulio Vargas - FGV/Tese_Mestrado/censo_1980/censo_pessoas_1980_bd.parquet")

estados <- c("RO", "AC", "AM", "RR", "PA", "AP")
data_1980_sem_ufs <- data_1980 %>%
  filter(!(v514 == "Só na zona rural" & sigla_uf %in% estados)) |> 
  filter(v606 >= 10)


```

## LFP (labor force productivity)
#### 1980

As autoras pegam o censo de 1970 e olham para lfp e tfr de 1950 já que estão tratando de imigrantes de segunda geração. No nosso caso iremos pegar esses dados de 1980/1990 quando olhamos para 2000.

```{r lfp 1980}

# numero de mulheres ocupadas com mais de 10 anos
teste <- data_1980[data_1980$v528 == 1 & data_1980$v606 >= 10 & data_1980$v501 == 3, ]
sum(teste$v604, na.rm = TRUE)

# numero oficial:  12 038 930 
# censo: 11 489 968

# calculo da pea para mulheres de 30-50 anos por uf
## https://seculoxx.ibge.gov.br/populacionais-sociais-politicas-e-culturais/busca-por-palavra-chave/populacao.html
pea_mulher_30_50 <- data_1980_sem_ufs |>
  filter((v528 == 1 | v528 == 3) & ((v606 >= 30 & v606 <= 39)) & v501 == 3)

soma_pea_mulher_30_50_por_uf <- pea_mulher_30_50 |>
  group_by(sigla_uf) |>
  summarize(soma_pea = sum(v604, na.rm = TRUE))


# oficial: 7145568
# censo: 7108364

### https://seculoxx.ibge.gov.br/populacionais-sociais-politicas-e-culturais/busca-por-palavra-chave/populacao.html
## oficial 30-49: 24709395
## censo: 25463744
n_30_39_anos <- data_1980_sem_ufs |>
  filter((v606 >= 30 & v606 <= 39))

soma_n_30_39_uf <- n_30_39_anos |>
  group_by(sigla_uf) |>
  summarize(soma_pop = sum(v604, na.rm = TRUE))

# taxa de participacao
f_lfp <- merge(soma_pea_mulher_30_50_por_uf, soma_n_30_39_uf, by = "sigla_uf") |> 
  mutate(lfp_1980 = soma_pea / soma_pop)

uf_codes <- c(
  "AC" = 12, "AL" = 27, "AM" = 13, "AP" = 16, "BA" = 29, 
  "CE" = 23, "DF" = 53, "ES" = 32, "FN" = NA, "GO" = 52, 
  "MA" = 21, "MG" = 31, "MS" = 50, "MT" = 51, "PA" = 15, 
  "PB" = 25, "PE" = 26, "PI" = 22, "PR" = 41, "RJ" = 33, 
  "RN" = 24, "RO" = 11, "RR" = 14, "RS" = 43, "SC" = 42, 
  "SE" = 28, "SP" = 35
)

f_lfp_1980 <- f_lfp |>
  mutate(uf_nascim = as.numeric(recode(sigla_uf, !!!uf_codes))) |>
  dplyr::select(-sigla_uf) |>
  filter(!is.na(uf_nascim))

write_xlsx(f_lfp_1980, "C:/Users/thtak/OneDrive - Fundacao Getulio Vargas - FGV/Tese_Mestrado/1_migration/1_datasets_migrants/lfp/f_lfp_1980.xlsx")
```

Números chegaram a participação de 50\% de mulheres entre 30-39 anos, enquanto os dados oficiais falam em 42,4\%

```{r divergencias tx participacao}
mean(f_lfp_1980$lfp_1980, na.rm = TRUE)
```


## Taxa fecundidade

#### tx fec 1980

```{r fec 1980}
tfr_datasus <- read_xlsx("C:/Users/thtak/OneDrive - Fundacao Getulio Vargas - FGV/Tese_Mestrado/1_migration/1_datasets_migrants/fecundidade_brasil/fecundidade_1960_2000_estados.xlsx")

tfr_1980 <- tfr_datasus |>
  dplyr::select(uf_nascim, "1980") |> 
  rename("1980_tfr" = "1980")

write_xlsx(tfr_1980, "C:/Users/thtak/OneDrive - Fundacao Getulio Vargas - FGV/Tese_Mestrado/1_migration/1_datasets_migrants/fecundidade_brasil/tfr_1980.xlsx")
```

