---
title: "Thais Takeuchi"
date: "30/8/24"
output: html_document
---

# Project: Análise 1970

# CENSO NÃO COMPATIBILIZADO (BD)

```{r setup, include=FALSE}
# Limpar o ambiente, mantendo apenas o objeto "cp2000"
rm(list = (ls()))

# Pacotes necessários
load.lib <- c("data.table","foreign","stargazer","devtools","stringi", 
              "srvyr", "survey","tidyverse","gtools", "remote",
              "installr","microdadosBrasil","ggplot2","viridis",
              "hrbrthemes","WDI","dplyr", "arrow", "readxl","rio",
              "writexl","dineq", "basedosdados", "httr", "haven", 
              "openxlsx", "fixest","car", "htmltools")

# Instalar e carregar pacotes
install.lib <- load.lib[!load.lib %in% installed.packages()]
for(lib in install.lib) install.packages(lib, dependencies = TRUE)
sapply(load.lib, require, character = TRUE)

```


```{r carrega base}
# Carregar dados do censo de 1970 em formato Parquet
# df <- read_dta("E:/Thais/Tese_Mestrado/censo_1970/censo_pessoas_1970_filtrado_nao_comp.dta")
# 
# write_parquet(df, "E:/Thais/Tese_Mestrado/censo_1970/censo_pessoas_1970_filtrado_nao_comp.parquet")
df <- read_parquet("E:/Thais/Tese_Mestrado/censo_1970/censo_pessoas_1970_filtrado_bd.parquet")

```

```{r carrega base apoio}
### Cultural proxies----

## Taxa de divorcio no país de origem (1970)
home_country_div_rate_1970 <- read_xlsx("E:/Thais/Tese_Mestrado/tese_bases/home_country_div_rate/home_country_div_rate_1970.xlsx")

## Country of Origin Variables, measured in the year 1970 except where otherwise noted (paper)----

## GDP per capita
gdp_pc_1970 <- read_xlsx("E:/Thais/Tese_Mestrado/tese_bases/gdp_per_capita/gdp_pc_1970.xlsx")

## Average Female Age at First Marriage
mean_age_fmarr_1970 <- read_xlsx("E:/Thais/Tese_Mestrado/tese_bases/age_first_marriage/mean_age_fmarr_1970.xlsx")

## Total fertility rate
fertility_rate_1970 <- read_xlsx("E:/Thais/Tese_Mestrado/tese_bases/fertility_rate/fertility_rate_1970.xlsx")
```

## MANIPULAÇÕES

```{r manipula}
# Renomeando países de origem
df <- df %>% rename(pais_nascim = v030)

setDT(df)

df <- df %>%
  mutate(pais_nascim = case_when(
    pais_nascim == 30 ~ "ARG",
    pais_nascim == 31 ~ "BOL",
    pais_nascim == 32 ~ "CAN",
    pais_nascim == 33 ~ "CHL",
    pais_nascim == 34 ~ "COL",
    pais_nascim == 35 ~ "CRI",
    pais_nascim == 36 ~ "CUB",
    pais_nascim == 37 ~ "ECU",
    pais_nascim == 38 ~ "USA",
    pais_nascim == 39 ~ "GTM",
    pais_nascim == 40 ~ "GUY",
    pais_nascim == 41 ~ "GUF",
    pais_nascim == 42 ~ "HTI",
    pais_nascim == 43 ~ "HND",
    pais_nascim == 44 ~ "BLZ",
    pais_nascim == 45 ~ "JAM",
    pais_nascim == 46 ~ "MEX",
    pais_nascim == 47 ~ "NIC",
    pais_nascim == 48 ~ "PAN",
    pais_nascim == 49 ~ "PRY",
    pais_nascim == 50 ~ "PER",
    pais_nascim == 51 ~ "DOM",
    pais_nascim == 52 ~ "SLV",
    pais_nascim == 53 ~ "SUR",
    pais_nascim == 54 ~ "URY",
    pais_nascim == 55 ~ "VEN",
    pais_nascim == 56 ~ "OTH_AM",
    pais_nascim == 58 | pais_nascim == 57 ~ "DEU",
    pais_nascim == 59 ~ "AUT",
    pais_nascim == 60 ~ "BEL",
    pais_nascim == 61 ~ "BGR",
    pais_nascim == 62 ~ "DNK",
    pais_nascim == 63 ~ "ESP",
    pais_nascim == 64 ~ "FIN",
    pais_nascim == 65 ~ "FRA",
    pais_nascim == 66 ~ "GBR",
    pais_nascim == 67 ~ "GRC",
    pais_nascim == 68 ~ "NLD",
    pais_nascim == 69 ~ "HUN",
    pais_nascim == 70 ~ "IRL",
    pais_nascim == 71 ~ "ITA",
    pais_nascim == 72 ~ "YUG",
    pais_nascim == 73 ~ "NOR",
    pais_nascim == 74 ~ "POL",
    pais_nascim == 75 ~ "PRT",
    pais_nascim == 76 ~ "ROU",
    pais_nascim == 77 ~ "SWE",
    pais_nascim == 78 ~ "CHE",
    pais_nascim == 79 ~ "CZE",
    pais_nascim == 80 ~ "RUS",
    pais_nascim == 81 ~ "OTH_EUR",
    pais_nascim == 82 ~ "AGO",
    pais_nascim == 83 ~ "EGY",
    pais_nascim == 84 ~ "MOZ",
    pais_nascim == 85 ~ "OTH_AFR",
    pais_nascim == 86 ~ "CHN",
    pais_nascim == 87 ~ "TWN",
    pais_nascim == 88 ~ "KOR",
    pais_nascim == 89 ~ "IND",
    pais_nascim == 90 ~ "ISR",
    pais_nascim == 91 ~ "JPN",
    pais_nascim == 92 ~ "LBN",
    pais_nascim == 93 ~ "PAK",
    pais_nascim == 94 ~ "SYR",
    pais_nascim == 95 ~ "TUR",
    pais_nascim == 96 ~ "OTH_ASIA",
    pais_nascim == 97 ~ "AUS",
    pais_nascim == 98 ~ "OTH_OCE",
    pais_nascim == 99 ~ "NO_SPEC",
    TRUE ~ as.character(pais_nascim)
  ))

```

```{r manipula 2}

df$ano <- 1970

# separados, divorciados e desquitados
df <- df %>%
  mutate(
    ano_nasc = ano - v027,
    imm = ifelse(v029 %in% c(1,2), 1, 0), #tempo de residência nessa uf
    # 6 - separado, 7 - desquitado e 8 - divorciado
    imm_div = ifelse(imm == 1
                     & v040 %in% c(6,7,8), 1, 0),
  )

# so divorciados
# df <- df %>%
#   mutate(
#     ano_nasc = ano - v027,
#     imm = ifelse(V516 == 7, 1, 0),
#     imm_div = ifelse(imm == 1
#                      & V526 %in% c(8), 1, 0),
#   )

# se imm_div e NA entao coloca zero
df$imm_div[is.na(df$imm_div)] <- 0

df <- df %>%
  mutate(
    imm_homem = ifelse(v023 == "0"
                       & imm == 1, 1, 0),
    imm_alf = ifelse(imm == 1 & (v035 == 1), 1, 0), 
    imm_fund_completo = ifelse(imm == 1
                               & (v038 == "Ginasial/medio 1º ciclo"), 1, 0), 
    imm_em_completo = ifelse(imm == 1
                             & (v038 == "Ginasial/medio 2º ciclo"), 1, 0), 
    imm_superior_completo = ifelse(imm == 1
                                   & (v038 == "Superior"), 1, 0), 
    imm_mulher1filho = ifelse(imm == 1 #sem informacao da idade do filho
                              & v023 == "1"
                              & (v050 >= 1), 1, 0)
  )

```

```{r merge}
# Juntando as bases

# df com home country divorce rate
df_1 <- merge(df, home_country_div_rate_1970, by = "pais_nascim", all.x = TRUE)

df_2 <- merge(df_1, gdp_pc_1970, by = "pais_nascim", all.x = TRUE)

# com age_f_first_marriage
df_3 <- merge(df_2, mean_age_fmarr_1970, by = "pais_nascim", all.x = TRUE)

# com fertility_rate
df_4 <- merge(df_3, fertility_rate_1970, by = "pais_nascim", all.x = TRUE)

```

```{r manipula 3}
# Tirando outros paises (...-others e paises com NA)----
df_4 <- df_4 %>% 
  filter(!`pais_nascim` %in% c("OTH_AFR", "OTH_AM", "OTH_ASIA","OTH_EUR", "OTH_OCE"))

df_4 <- df_4 %>% rename(escolaridade = v038)

# transforma escolaridade em continua
# df_4$escolaridade_cont <- as.numeric(df_4$escolaridade) #< table of extent 0 >

# idade ao quadrado
df_4 <- df_4 %>%
  mutate(
    age_fem = if_else(v023 == "1", v027, NA_real_),
  ) %>%
  mutate(
    age_squared = v027^2
  )

# Remove valores NA na coluna de pais_nascim e hcdr
df_4 <- df_4[!is.na(df_4$pais_nascim), ]
df_4 <- df_4[!is.na(df_4$hcdr), ]

df_4 <- df_4 |> rename(wage = v041) #Rendimento médio mensal

df_4 <- df_4 |> 
  mutate(
    annual_wage = wage * 12,
    log_wage = log(annual_wage),
    wage_fem = ifelse(imm == 1 & v023 == "1", annual_wage, 0), 
    log_wage_fem = log(ifelse(is.na(wage_fem), 0, wage_fem)), 
    wage_men = ifelse(imm == 1 & v023 == "0", annual_wage, 0), #verificar
    log_wage_men = log(ifelse(is.na(wage_men), 0, wage_men)) 
  )
```



```{r adiciona variaveis}
base_partial_nc_1970 <- as.data.frame(df_4)
# write_xlsx(base_partial_nc_1970, "E:/Thais/Tese_Mestrado/tese_bases/base_gerada/base_nc_1970.xlsx")

setDT(base_partial_nc_1970)
```


```{r 1}
## Rodando a regressao (1) - table 2
# FE: idade
model1_nc <- feols(imm_div ~ hcdr + imm_homem + imm_fund_completo + imm_em_completo + imm_superior_completo | factor(v027)+ age_squared, data = base_partial_nc_1970, weights = ~v054, cluster = ~pais_nascim)
summary(model1_nc)
```


```{r 2}
# Drop Portugal (3)
base_partial_nc_sem_portugal <- base_partial_nc_1970 %>%
  filter(pais_nascim != "PRT")

model2_nc_sem_portugal <- feols(imm_div ~ hcdr + imm_homem + imm_fund_completo + imm_em_completo + imm_superior_completo | factor(v027)+age_squared, data = base_partial_nc_sem_portugal, weights = ~v054, cluster = ~pais_nascim)
summary(model2_nc_sem_portugal)
```

```{r 5}
# Drop Russia and Italy (4)
base_partial_nc_sem_russia_italy <- base_partial_nc_1970 %>%
  filter(pais_nascim != "ITA") |> 
  filter(pais_nascim != "RUS")

model2_nc_sem_russia_italy <- feols(imm_div ~ hcdr + imm_homem + imm_fund_completo + imm_em_completo + imm_superior_completo | factor(v027)+age_squared, data = base_partial_nc_sem_russia_italy, weights = ~v054, cluster = ~pais_nascim)
summary(model2_nc_sem_russia_italy)
```
